

//typedef nvmlReturn_t ( *NVML_DEVICE_CLEAR_ACCOUNTING_PIDS ) (int iAdapterIndex, ADLMemoryInfo *lpMemoryInfo);


/*
U nvmlDeviceClearAccountingPids
U nvmlDeviceClearEccErrorCounts
U nvmlDeviceGetAccountingBufferSize
U nvmlDeviceGetAccountingMode
U nvmlDeviceGetAccountingPids
U nvmlDeviceGetAccountingStats
U nvmlDeviceGetAPIRestriction
U nvmlDeviceGetApplicationsClock
U nvmlDeviceGetBAR1MemoryInfo
U nvmlDeviceGetBridgeChipInfo
U nvmlDeviceGetClockInfo
U nvmlDeviceGetComputeMode
U nvmlDeviceGetComputeRunningProcesses
U nvmlDeviceGetCount_v2
U nvmlDeviceGetCurrentClocksThrottleReasons
U nvmlDeviceGetCurrPcieLinkGeneration
U nvmlDeviceGetCurrPcieLinkWidth
U nvmlDeviceGetDefaultApplicationsClock
U nvmlDeviceGetDetailedEccErrors
U nvmlDeviceGetDisplayActive
U nvmlDeviceGetDisplayMode
U nvmlDeviceGetDriverModel
U nvmlDeviceGetEccMode
U nvmlDeviceGetEnforcedPowerLimit
U nvmlDeviceGetFanSpeed
U nvmlDeviceGetGpuOperationMode
U nvmlDeviceGetHandleByIndex_v2
U nvmlDeviceGetHandleByPciBusId_v2
U nvmlDeviceGetHandleBySerial
U nvmlDeviceGetHandleByUUID
U nvmlDeviceGetIndex
U nvmlDeviceGetInforomConfigurationChecksum
U nvmlDeviceGetInforomImageVersion
U nvmlDeviceGetInforomVersion
U nvmlDeviceGetMaxClockInfo
U nvmlDeviceGetMaxPcieLinkGeneration
U nvmlDeviceGetMaxPcieLinkWidth
U nvmlDeviceGetMemoryErrorCounter
U nvmlDeviceGetMemoryInfo
U nvmlDeviceGetMinorNumber
U nvmlDeviceGetName
U nvmlDeviceGetPciInfo_v2
U nvmlDeviceGetPerformanceState
U nvmlDeviceGetPersistenceMode
U nvmlDeviceGetPowerManagementDefaultLimit
U nvmlDeviceGetPowerManagementLimit
U nvmlDeviceGetPowerManagementLimitConstraints
U nvmlDeviceGetPowerManagementMode
U nvmlDeviceGetPowerState
U nvmlDeviceGetPowerUsage
U nvmlDeviceGetRetiredPages
U nvmlDeviceGetRetiredPagesPendingStatus
U nvmlDeviceGetSerial
U nvmlDeviceGetSupportedClocksThrottleReasons
U nvmlDeviceGetSupportedEventTypes
U nvmlDeviceGetSupportedGraphicsClocks
U nvmlDeviceGetSupportedMemoryClocks
U nvmlDeviceGetTemperature
U nvmlDeviceGetTotalEccErrors
U nvmlDeviceGetUtilizationRates
U nvmlDeviceGetUUID
U nvmlDeviceGetVbiosVersion
U nvmlDeviceOnSameBoard
U nvmlDeviceRegisterEvents
U nvmlDeviceResetApplicationsClocks
U nvmlDeviceSetAccountingMode
U nvmlDeviceSetAPIRestriction
U nvmlDeviceSetApplicationsClocks
U nvmlDeviceSetComputeMode
U nvmlDeviceSetDriverModel
U nvmlDeviceSetEccMode
U nvmlDeviceSetGpuOperationMode
U nvmlDeviceSetPersistenceMode
U nvmlDeviceSetPowerManagementLimit
U nvmlDeviceValidateInforom
U nvmlErrorString
U nvmlEventSetCreate
U nvmlEventSetFree
U nvmlEventSetWait
U nvmlInit_v2
U nvmlShutdown
U nvmlSystemGetDriverVersion
U nvmlSystemGetHicVersion
U nvmlSystemGetNVMLVersion
U nvmlSystemGetProcessName
U nvmlUnitGetCount
U nvmlUnitGetDevices
U nvmlUnitGetFanSpeedInfo
U nvmlUnitGetHandleByIndex
U nvmlUnitGetLedState
U nvmlUnitGetPsuInfo
U nvmlUnitGetTemperature
U nvmlUnitGetUnitInfo
U nvmlUnitSetLedState
*/
